### Get All Tasks
GET http://localhost:8080/tasks

### Create a New Task
POST http://localhost:8080/tasks
Content-Type: application/json

{
    "title": "New Task",
    "description": "Task description",
    "is_completed": false
}

### Update a Task
PUT http://localhost:8080/tasks/2
Content-Type: application/json

{
    "title": "Updated Task",
    "description": "Updated description",
    "is_completed": true
}

### Delete a Task
DELETE http://localhost:8080/tasks/2


### Create a New User
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "username": "saiful",
    "email": "saiful@example.com",
    "password": "securepassword"
}

### Login request
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "saiful@example.com",
    "password": "securepassword"
}