version: "3.8"

services:
  task-manager:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_DSN=host=postgres user=postgres password=postgres dbname=task_manager port=5432 sslmode=disable
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
    ports:
      - "5432:5436"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
