version: '3.8'
services:

  db:
    image: postgres:15
    container_name: task-manager-db
    environment:
      POSTGRES_USER: saiful
      POSTGRES_PASSWORD: saiful@soft_dev
      POSTGRES_DB: task_manager
    ports:
      - "5432:5434"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: task-manager-app
      
    ports:
      - "8080:8080"
    networks:
      - app_network
    environment:
      - DB_HOST=db
      - DB_USER=saiful
      - DB_PASSWORD=saiful@soft_dev
      - DB_NAME=task_manager
      - JWT_SECRET=02024963
    depends_on:
      - db

  

volumes:
  db_data:

networks:
  app_network:
    driver: bridge