version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=saiful
      - DB_PASSWORD=saiful@soft_dev
      - DB_NAME=task_manager
      - JWT_SECRET=02024963
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: saiful
      POSTGRES_PASSWORD: saiful@soft_dev
      POSTGRES_DB: task_manager
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
